# Generated by Django 2.2.14 on 2024-07-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sale', models.BooleanField(default=False)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
    ]
